<?php namespace ProcessWire;

/**
 *
 * Template Field Widths
 *
 * @author Robin Sallis
 *
 * ProcessWire 3.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TemplateFieldWidths extends WireData implements Module, ConfigurableModule {

	/**
	 * Module information
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Template Field Widths',
			'version' => '0.1.10',
			'summary' => 'Quickly set the widths of inputfields in a template.',
			'author' => 'Robin Sallis',
			'icon' => 'arrows-h',
			'autoload' => 'template=admin',
			'requires' => 'ProcessWire>=3.0.0'
		);
	}

	/**
	 * Ready
	 */
	public function __construct() {
		parent::__construct();
		$this->tfw_collapsed = 1;
		$this->field_identifier = 'name';
	}

	/**
	 * Ready
	 */
	public function ready() {
		$this->addHookAfter('ProcessTemplate::buildEditForm', $this, 'modifyEditForm');
		$this->addHookBefore('ProcessTemplate::executeSave', $this, 'applyWidths');
	}

	/**
	 * Add field to template edit form
	 *
	 * @param HookEvent $event
	 */
	protected function modifyEditForm(HookEvent $event) {
		/* @var InputfieldForm $form */
		$form = $event->return;
		$template = $this->getTemplate();
		$fieldgroup = $template->fieldgroup;
		$fg_fields = $form->getChildByName('fieldgroup_fields');
		// No need to continue if template gets its fields from a different fieldgroup
		if(!$fg_fields) return;

		// Tabs array
		$tabs = array();
		$content_tab_name = 'content';
		$content_tab_label = $template->tabContent ?: $this->_('Content');
		$tab_name = $content_tab_name;
		$tab_label = $content_tab_label;
		foreach($fieldgroup as $field) {
			if($field->type == 'FieldtypeFieldsetTabOpen' || ($field->type == 'FieldtypeFieldsetGroup' && $field->useTabs === 1)) {
				$tab_name = $field->name;
				$f = $fieldgroup->getFieldContext($field);
				$tab_label = $f->label ?: $tab_name;
				continue;
			}
			if($field->type == 'FieldtypeFieldsetClose' && $field->name == "{$tab_name}_END") {
				$tab_name = $content_tab_name;
				$tab_label = $content_tab_label;
				continue;
			}
			$tabs[$tab_name]['label'] = $tab_label;
			$tabs[$tab_name]['fields'][] = $field;
		}

		// Hidden input to record field opened/closed state
		$val = (int) !$this->tfw_collapsed;
		$markup = "<input type='hidden' id='tfw_open' name='tfw_open' value='$val'>";

		// Open container
		$markup .= "<div class='tfw-container'>";

		// Tabs
		$markup .= "<ul class='tfw-tabs'>";
		foreach($tabs as $tab_name => $tab_data) {
			$active = $tab_name === 'content' ? ' active' : '';
			$markup .= "<li class='tfw-tab{$active}' data-tab='tfw-{$tab_name}'>{$tab_data['label']}</li>";
		}
		$markup .= "</ul>";

		// Tab content
		$markup .= "<ul class='tfw-tabs-content'>";
		foreach($tabs as $tab_name => $tab_data) {
			$active = $tab_name === 'content' ? ' active' : '';
			$markup .= "<li id='tfw-{$tab_name}' class='tfw-tab-content{$active}'>";
			$markup .= "<div class='tfw-tab-wrap'>";
			foreach($tab_data['fields'] as $field) {
				// Close fieldset
				if($field->type == 'FieldtypeFieldsetClose') {
					$markup .= "</div></div>";
					continue;
				}
				$f = $fieldgroup->getFieldContext($field);
				$col_width = $f->columnWidth ?: 100;
				$is_fieldset = in_array($field->type, array('FieldtypeFieldsetOpen', 'FieldtypeFieldsetGroup'));
				$id = 'tfw_' . $f->name;
				$orig_width_markup = '';
				if($this->show_original_width) {
					$orig_width = $field->columnWidth ?: 100;
					$orig_width_markup = "<span class='orig-width'>{$orig_width}%</span>";
				}
				$primary_identifier = $this->field_identifier === 'name' ? $f->name : ($f->label ?: $f->name) ;
				if($is_fieldset) $primary_identifier = "<strong>$primary_identifier</strong>";
				$secondary_identifier = $this->field_identifier === 'name' ? $f->label : $f->name;
				$markup .= <<<EOT
<div class='tfw-item' style='width:{$col_width}%'>
	<label>
		<span class='tfw-label' title='$secondary_identifier'>$primary_identifier</span>
		<div class='tfw-input'>
			<input id='$id' name='$id' type='number' min='10' max='100' value='$col_width'>{$orig_width_markup}
		</div>
</label>
EOT;
				if($is_fieldset) {
					// Open fieldset
					$markup .= "<div class='tfw-fieldset'>";
				} else {
					$markup .= "</div>";
				}
			}
			$markup .= "</div>";
			$markup .= "</li>";
		}
		$markup .= "</ul>";

		// Close container
		$markup .= "</div>";

		/* @var InputfieldMarkup $f */
		$f = $this->wire('modules')->InputfieldMarkup;
		$f->name = 'inputfield_widths';
		$f->label = $this->_('Field widths');
		$f->icon = 'arrows-h';
		$f->value = $markup;
		if($this->tfw_collapsed) $f->collapsed = Inputfield::collapsedYes;
		$form->insertAfter($f, $fg_fields);

		// Load stylesheet and script
		$config = $this->wire('config');
		$info = $this->getModuleInfo();
		$version = $info['version'];
		$config->styles->add($config->urls->$this . "{$this}.css?v=$version");
		$config->scripts->add($config->urls->$this . "{$this}.js?v=$version");
	}

	/**
	 * Apply field widths
	 *
	 * @param HookEvent $event
	 */
	protected function applyWidths(HookEvent $event) {
		$template = $this->getTemplate();
		$fieldgroup = $template->fieldgroup;
		$input = $this->wire('input');
		// Return early if module inputfield was not open
		if(!$input->post->tfw_open) return;
		foreach($input->post as $key => $value) {
			if(substr($key, 0, 4) !== 'tfw_') continue;
			$field_name = substr($key, 4);
			$col_width = (int) $value;
			$f = $fieldgroup->getFieldContext($field_name);
			if(!$f || $f->columnWidth === $col_width || (!$f->columnWidth && $col_width === 100)) continue;
			$f->columnWidth = $col_width;
			$this->wire('fields')->saveFieldgroupContext($f, $fieldgroup);
		}
	}

	/**
	 * Get template from ID in $input
	 *
	 * @return Template|null
	 */
	protected function getTemplate() {
		$template_id = (int) $this->wire('input')->post->id ?: (int) $this->wire('input')->get->id;
		return $this->wire('templates')->get($template_id);
	}

	/**
	 * Config inputfields
	 *
	 * @param InputfieldWrapper $inputfields
	 */
	public function getModuleConfigInputfields($inputfields) {
		$modules = $this->wire('modules');

		/* @var InputfieldRadios $f */
		$f = $modules->InputfieldRadios;
		$f_name = 'tfw_collapsed';
		$f->name = $f_name;
		$f->label = $this->_('Presentation of Template Field Widths field');
		$f->notes = $this->_('"Collapsed" recommended if you might also use core inputs for setting field widths.');
		$f->addOption(1, $this->_('Collapsed'));
		$f->addOption(0, $this->_('Open'));
		$f->optionColumns = 1;
		$f->value = $this->$f_name;
		$f->columnWidth = 40;
		$inputfields->add($f);

		/* @var InputfieldRadios $f */
		$f = $modules->InputfieldRadios;
		$f_name = 'field_identifier';
		$f->name = $f_name;
		$f->label = $this->_('Field primary identifier');
		$f->addOption('name', $this->_('Name'));
		$f->addOption('label', $this->_('Label'));
		$f->optionColumns = 1;
		$f->value = $this->$f_name;
		$f->columnWidth = 30;
		$inputfields->add($f);

		/* @var InputfieldCheckbox $f */
		$f = $modules->InputfieldCheckbox;
		$f_name = 'show_original_width';
		$f->name = $f_name;
		$f->label = $this->_("Show each field's original width");
		$f->checked = $this->$f_name === 1 ? 'checked' : '';
		$f->columnWidth = 30;
		$inputfields->add($f);

	}

}
